version: '3.9'

networks:
  incidents_net:

volumes:
  db_data:

services:
  db:
    image: postgres:16
    container_name: incidents_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-incidents_db}
      POSTGRES_USER: ${POSTGRES_USER:-incidents_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-incidents_pass}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - incidents_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-incidents_user} -d ${POSTGRES_DB:-incidents_db} -h localhost -p 5432 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      [
        "sh","-lc",
        "set -e; \
         mvn -q -DskipTests \
            -Dflyway.url=jdbc:postgresql://db:5432/${POSTGRES_DB:-incidents_db} \
            -Dflyway.user=${POSTGRES_USER:-incidents_user} \
            -Dflyway.password=${POSTGRES_PASSWORD:-incidents_pass} \
            flyway:repair flyway:migrate"
      ]
    networks:
      - incidents_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incidents_api
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    networks:
      - incidents_net
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: incidents_web
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4200:80"
    networks:
      - incidents_net
