spring:
  application:
    name: incidents
  datasource:
    url: jdbc:postgresql://localhost:5434/incidents_db
    username: incidents_user
    password: incidents_pass
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5434/incidents_db
    user: incidents_user
    password: incidents_pass
  data:
    rest:
      default-media-type: application/json
  web:
    pageable:
      default-page-size: 10
      max-page-size: 100
  jackson:
    default-property-inclusion: NON_NULL

jwt:
  secret: L9k9M9W9bQXdd6cojXruU2pZTd7rsiAjpCB
  expiration: 86400000
