spring:
  datasource:
    url: jdbc:postgresql://db:5432/incidents_db
    username: incidents_user
    password: incidents_pass
  flyway:
    enabled: true
    url: jdbc:postgresql://db:5432/incidents_db
    user: incidents_user
    password: incidents_pass
